### ISSUE TITLE
ER: Downloading Auto Reply

### ISSUE THREAD

**Issue by bakerboy448** [bakerboy448/arrsubreddit#10]
If downloading in title auto reply with something like  https://www.reddit.com/r/sonarr/comments/i1ek9h/comment/fzwws5g

**Comment by Drazzilb08** [comment]
we could do something like

type: comment
title+body: ["download"]
comment: "blah blah blah"

testing needed

**Comment by Drazzilb08** [comment]
# 7.5 #Auto reply if "Downloads, Downloading, Download" is in the body or the title
type: submission
Title+body: ["Download", "Downloading", "Download"]
comment: " Hi. OP! It appears that you're having issues w/ some aspect of downloading please review the following link. [Downloading & Importing](https://github.com/Sonarr/Sonarr/wiki/Downloads-and-Importing) The link is for Sonarr, but the concepts apply for {{subreddit}}."

---

Added this bit of code as a #7.5 it will do this.
