### ISSUE TITLE
#10# w/in ARRmodTest

### ISSUE THREAD

**Issue by Drazzilb08** [bakerboy448/arrsubreddit#11]
#10 w/in arrmodtest needs tweaking. 

`# 10 #Solved Comment for help post
type: comment
body: ["!solved"]
author:
  is_submitter: true
parent_submission:
  set_flair:
    template_id: 16d2d504-d378-11ea-a0ae-0e7365d88ae9
  overwrite_flair: true
comment: "Thank you/u/{{author}} we hope that if you have any further issues you'll come back and ask away."
---`
Right now any person that posts !solved regardless of the flair or situation will have the flair changed to solved and will have the comment posted. 

Ideally #10 should only work if the flair is set to unsolved in order to change it to solved.

**Comment by Drazzilb08** [comment]
essentially what I'm looking to do is have an && statement 

- If post flair is set to unsolved && author is the submitter of the comment !solved then set flair to solved

**Comment by Drazzilb08** [comment]
https://www.reddit.com/r/AutoModerator/comments/huowng/making_automod_work_only_on_a_post_with_a_certain/?utm_source=share&utm_medium=ios_app&utm_name=iossmf


Worth a look

**Comment by bakerboy448** [comment]
author: is_submitter: true   should cover it

This is were I'm borrowing from
https://pastebin.com/Pm1XdnMa

**Comment by Drazzilb08** [comment]
solved. Part of the issue was ensuring that if another flair was posted say "idea" then if anybody used !solved it wouldn't trigger auto mod
