### ISSUE TITLE
BROKE: Autoflair if no flair not working

### ISSUE THREAD

**Issue by bakerboy448** [bakerboy448/arrsubreddit#24]
Radarr for sure; not sure on the rest
https://www.reddit.com/r/radarr/comments/i457ea/radarr_not_finding_movies_on_my_server/
I flaired manually

**Comment by bakerboy448** [comment]
it replied here, but didn't set the flair https://www.reddit.com/r/Lidarr/comments/i4844t/anyone_got_a_working_lidarrbeets_workflow/

**Comment by bakerboy448** [comment]
Radarr had the arrtest NOT commented out; likely implementation error

**Comment by bakerboy448** [comment]
still occuring
https://www.reddit.com/r/radarr/comments/i8yhw8/radarr_docker_and_mergerfs_radarr_not_seeing/
![image](https://user-images.githubusercontent.com/55419169/90171550-48bdf500-dd67-11ea-9cf5-04a18d4ec4bd.png)

**Comment by bakerboy448** [comment]
https://www.reddit.com/r/sonarr/comments/igdx7i/is_there_away_to_ignore_thexem_mapping_and_just/

Yup it comments, but does not touch the flair?

**Comment by Drazzilb08** [comment]
Not sure what's wrong with this one. I'll have to test it out

**Comment by bakerboy448** [comment]
yeah, it /should/ work? but something isn't right.

**Comment by Drazzilb08** [comment]
updated with #33
