### ISSUE TITLE
BROKE: !solved doesn't work

### ISSUE THREAD

**Issue by bakerboy448** [bakerboy448/arrsubreddit#25]
https://www.reddit.com/r/radarr/comments/i46dp7/different_folder_for_kids/g0ge07p?utm_source=share&utm_medium=web2x

**Comment by bakerboy448** [comment]
https://www.reddit.com/r/radarr/comments/ibivxt/adding_tags_to_movies_from_lists_movies_already/

Still a bug

**Comment by bakerboy448** [comment]
https://www.reddit.com/r/sonarr/comments/igdx7i/is_there_away_to_ignore_thexem_mapping_and_just/

**Comment by Drazzilb08** [comment]
updated with #33
