### ISSUE TITLE
BROKE: No Logs Auto Reply; Pastebin not formatted

### ISSUE THREAD

**Issue by bakerboy448** [bakerboy448/arrsubreddit#26]
\[pastebin link\]\(pastebin.com\) is what is displayed
https://www.reddit.com/r/sonarr/comments/i542g8/all_indexers_keep_failing/g0mji0h/

**Comment by Drazzilb08** [comment]
more information needed. will talk to you about this one.

**Comment by bakerboy448** [comment]
it's displaying as the markup and not as "pastebin link" as a link

**Comment by Drazzilb08** [comment]
Oh I found it. Must be too dang tired now. Easy fix when. I get time.
