### ISSUE TITLE
Possibly add nzb drone to log list

### ISSUE THREAD

**Issue by Drazzilb08** [bakerboy448/arrsubreddit#28]
https://www.reddit.com/r/radarr/comments/i5zygb/radarr_not_adding_year_to_some_movie_folders/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

Either add to list for the no-log reply or the remove post with log in post

**Comment by bakerboy448** [comment]
ideally we don't have any logs in OP's post at all.
